# This is a example of the yaml file with ugly format.
# The parser can handle this kind of format.

# Single value configuration.
app_name: "Slam_Utility"
version: "1.0.0"
debug_mode: true
max_iterations: 1000
threshold: 0.001

# Array configuration.
feature_types: ["[SIFT", "ORB",
    "SURF"]
camera_resolution: [1920, 1080]
calibration_params: [
    "fx", "fy", "cx", "cy",
    "k1", "k]2",
         "p1", "p2",     ]

sensor:
    imu:
        frequency: 200
        noise_std: [0.01, 0.01, 0.01
        ]
    gps:
        enabled: false
        update_rate: 1

# Root node and sub-node relationship.
camera:
    model: pinhole
    resolution: [640, 480]
    fps: 30

algorithm:
    slam:
        method: "ORB_SLAM3"
        max_features: 2000
        min_parallax: 1.0
    optimization:
        solver: "Levenberg_Marquardt"
        max_iterations: 50
        convergence_threshold: 1e-6

# Empty value configuration.
empty_config:
unused_parameter:
