#!/bin/sh
sh push_repo.sh Slam_Utility "slam utility"
sh push_repo.sh Feature_Detector "feature detector"
sh push_repo.sh Feature_Tracker "feature tracker"
sh push_repo.sh Image_Processor "image processor"
sh push_repo.sh Sensor_Model "sensor model"
sh push_repo.sh Slam_Solver "slam solver"
sh push_repo.sh Visual_Frontend "visual frontend"
sh push_repo.sh Vision_Geometry "vision geometry"
sh push_repo.sh VIO_Stereo_ORB_SLAM3 "vio stereo orb slam3"
